#!/usr/bin/env bash
# This script will install nginx on web-01 server

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
