#!/usr/bin/env bash
# shellcheck disable=SC2154
# This script installs and configure ngnix to contain a response with a custom header.

sudo apt update
sudo apt install nginx -y
sudo sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
