#!/usr/bin/env bash
# this script will continue print infinity and beyond 
# even when a kill system call is been called 
trap 'echo "I am invincible!!!"' 15
while true
do
	echo "to infinity and beyond"
	sleep 2
done
