#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
count=0
max=10

while [ $count -lt $max ]
do
       if [ $count -eq 9 ]
       then
	       echo "Hi"
	fi	
       	echo "Best School"
        ((count++))
done
