#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
count=0
max=10

while [ $count -lt $max ]
do
       if [ $count -eq 4 ]
       then
               echo "bad luck"
       elif [ $count -eq 8 ]
	then
	       echo "good luck"
      else
        echo "Best School"
       fi
        ((count++))
done
